apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    app: user
    project: roboshop
    tier: app
  ports:
  - name: user
    protocol: TCP
    port: 8080     # service port 
    targetPort: 8080  # container port 