apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels: # these labels are deployment labels
    app: user
    project: roboshop
    tier: app 
spec:
  replicas: {{ .Values.deploymnet.replicas}}
  selector:
    matchLabels: # replicaset labels, these labels are used to find the pods
      app: user
      project: roboshop
      tier: app
  template:    # pod labels 
    metadata:
      labels:
        app: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: "joindevops/user:{{ .Values.deploymnet.imageVersion}}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
          - configMapRef:
              name: user
          
