apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ== # echo -n Roboshop@1 | base64  
  MYSQL_USER: c2hpcHBpbmc=               # echo -n c2hpcHBpbmc= | base64 --decode
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==