apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    app: payment
    project: roboshop
    tier: app
  ports:
  - name: payment
    protocol: TCP
    port: 8080     # service port 
    targetPort: 8080  # container port 