apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    app: cart
    project: roboshop
    tier: app
  ports:
  - name: cart
    protocol: TCP
    port: 8080     # service port 
    targetPort: 8080  # container port 